const path = require('path');
const fs = require('fs');

// Path to the standalone server generated by Next.js
const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

if (fs.existsSync(standaloneServerPath)) {
  console.log('Starting Next.js standalone server...');
  require(standaloneServerPath);
} else {
  console.error('Standalone server not found. Please run "npm run build" first with output: "standalone" in next.config.ts.');
  process.exit(1);
}
